### ISSUE TITLE
How to transfer visual from old PBI core to new environment

### ISSUE THREAD

**Issue by yiwsun** [Microsoft/PowerBI-visuals-core#487]
I want to use the "HeatMap" custom visual here https://github.com/sjkp/PowerBI-visuals. but it failed to build with errors:
ERROR in ./src/Clients/PowerBIVisualsPlayground/sampleData.ts
(53,33): error TS2339: Property 'MapByYearData' does not exist on type 'typeof sampleDataViews'.

ERROR in ./src/Clients/Visuals/plugins.ts
(356,23): error TS2304: Cannot find name 'HeatMapChart'.

ERROR in ./src/Clients/Visuals/plugins.ts
(357,27): error TS2304: Cannot find name 'HeatMapChart'.
[05:52:38] 'build' errored after 1.12 min

I tried to manually add MapData.ts in  src\Clients\PowerBIVisualsPlayground_references.ts
and heatMap.ts   in src\Clients\Visuals_references.ts
Which resolved the above errors but brought up new errors:
ERROR in ./src/Clients/Visuals/visuals/heatMap.ts
(148,39): error TS2345: Argument of type 'string' is not assignable to parameter of type 'number'.

ERROR in ./src/Clients/Visuals/visuals/heatMap.ts
(154,13): error TS2322: Type 'Uint8ClampedArray' is not assignable to type 'number[]'.
  Property 'push' is missing in type 'Uint8ClampedArray'.

ERROR in ./src/Clients/Visuals/visuals/heatMap.ts
(352,33): error TS2345: Argument of type '{ x: string | number | boolean | Date; y: string | number | boolean | Date; i: string | number | ...' is not assignable to parameter of type 'HeatMapData'.
  Types of property 'x' are incompatible.
    Type 'string | number | boolean | Date' is not assignable to type 'number'.
      Type 'string' is not assignable to type 'number'.
[06:51:54] 'build' errored after 1.15 min

Any idea on how to fix those errors? Thanks!

**Comment by sjkp** [comment]
You can close this, I fixed the original repo.

**Comment by yiwsun** [comment]
Thank you Simon
